### ISSUE TITLE
Can you recommend any good and affordable IP services, or even free ones?

### ISSUE THREAD

**Issue by hdp198** [Zlkcyber/oasis-bot#3]
Can you recommend any good and affordable IP services, or even free ones?

**Comment by Araara7** [comment]
https://www.proxyjet.io?ref=nwm0yzl

buy from this

work for , grass, nodepay, oasis, and all

**Comment by xinzhongyouhai** [comment]
https://www.webshare.io/?referral_code=o425y6tgeis3
It’s cheaper and more stable here~
